spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板

blogs:
  baseDir: ${BLOG_BASE_DIR}

logging:
  level:
    root: INFO
  file:
    name: ${LOG_FILE_PATH}
